<?php
use Drupal\block\Entity\Block;
use Drupal\Core\Session\AccountInterface;
use Drupal\node\NodeInterface;
use Drupal\Core\Access\AccessResult;

// Hook function to provide the access to display block based on content type
function barcode_block_block_access(Block $block, $operation, AccountInterface $account)
{
	
	if ($operation == 'view')
	{
		if($block->id() == 'myblock')
		{
			//$roles = \Drupal::currentUser()->getRoles();
			//anonymous
			//adminstrator
			//Now based on Node Pages, Hide the block
			$node = \Drupal::routeMatch()->getParameter('node');
			if (($node instanceof \Drupal\node\NodeInterface) && ($node->gettype() != 'juggad_patches')  )
			{
				//Hiding the block if the node is not 'technologyarticle' type
				return AccessResult::forbiddenIf(true)->addCacheableDependency($block);
			}
			
			
		}
	}
}
		